name: survey_plans
description: A Flutter app to manage cadastral survey plans (desktop + mobile) with Firebase.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.2.1
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

